### ISSUE TITLE
Help menu points to Electron pages

### ISSUE THREAD

**Issue by ckerr** [CryptoUnited/Sapling#8]
The help submenu at https://github.com/CryptoUnited/Sapling/blob/master/app/menu.js#L97 points to Electron's pages rather than Sapling's, which might be more useful, e.g.

```diff
- { label: 'Search Issues', click() { shell.openExternal('https://github.com/atom/electron/issues'); } }
+ { label: 'Search Issues', click() { shell.openExternal('https://github.com/CryptoUnited/Sapling/issues'); } }
```

That way, bugs like [this one](https://github.com/electron/electron/issues/11821) will get reported in the right place. :smile:

**Comment by Greg-Griffith** [comment]
fixed in 5d1105d0c19271ddb824698f94c0e5a82e51da6f
thank you!
